version: '3.3'
services:
  mysql:
    container_name: MySQL_Container
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=somedbname
      - MYSQL_USER=someusername
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_ROOT_PASSWORD=somepasswordtoroot
    volumes:
      - type: bind
        source: ./conf
        target: /etc/mysql/conf.d' 
      - type: bind
        source: ./mysqldatapersist
        target : /var/lib/mysql
      # - 'persistent:/var/lib/mysql'
      # - './conf:/etc/mysql/conf.d'
    networks:
      - default
volumes:
  persistent: null
